server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3309/my_batch
    username: root
    password: my

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  batch:
    job:
      enabled: false
